for kk=1:length(k_min)
    for k=k_min(kk):k_max(kk)
        kkk=k-400*(kk-1);
        strcat([num2str(i),' ',...
            num2str(j),' ',...
            num2str(k),' ',...
            num2str(kk),' ',...
            num2str(kkk)])
    end
end